apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flag-service-secret
  namespace: togglemaster
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: flag-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: togglemaster/flag-service
